### PR TITLE
Add support for the Eiffel Tower underwater dataset

### PR DESCRIPTION
**Pull request by clementinboittiaux**
Hi @ebrach,

We recently published a dataset for long-term visual localization in underwater scenarios called Eiffel Tower. The dataset embeds four different visits of the same hydrothermal vent between 2015 and 2020. It is available at https://www.seanoe.org/data/00810/92226/.

The associated paper describing the dataset will be published shortly. To put in simply, the dataset was created using the following pipeline:
- Models are first built independently for each year with the help of the vehicle's navigation data.
- They are then registered in a common reference frame using TEASER++ (https://github.com/MIT-SPARK/TEASER-plusplus) and ICP.
- A global model embedding images of all visits is then built with the help of individual models that are now in the same reference frame.

The whole code was tested on Ubuntu 20.04.

We created a quick visualization tool (https://github.com/clementinboittiaux/dsacstar/blob/visualization/datasets/visualization.ipynb) to check that the inputs created by our script are consistent with the ones created by the Cambridge Landmarks script. Input camera poses and their observed 3D coordinates are in red.

Cambridge Landmarks - King's College:

https://user-images.githubusercontent.com/74063264/228846112-228c1fe2-2818-46ac-8aec-a68baa570bdf.mp4

<br>

Eiffel Tower:

https://user-images.githubusercontent.com/74063264/228847811-37a3588e-801b-4f45-ac80-a9a00d63f7fb.mp4

<br>

Feel free to ask if you have any questions.

### CODE REVIEW

**Comment by ebrach** [comment]
Hi Clémentin,

sounds like a great effort! Would it be possible to read a pre-print of the associated paper, or ping me again if it is publicly available?

Best,
Eric

**Comment by clementinboittiaux** [comment]
Hi Eric,

We just got the reviews, we will make it available in a few weeks, I'll ping you again when it is available!

Best,
Clémentin

**Comment by clementinboittiaux** [comment]
Hi @ebrach,

The data paper is now available on arxiv: https://arxiv.org/abs/2305.05301
Don't hesitate if you have any questions!

Best,
Clémentin

**Comment by clementinboittiaux** [comment]
Hi @ebrach,

The data paper has been published on IJRR website: https://doi.org/10.1177/02783649231177322
Do you think it would be ok to merge?

Best,
Clémentin

**Comment by ebrach** [comment]
Hi Clémentin, congratulations on the journal paper! As said before, the dataset looks very interesting.

In terms of the DSAC* repository, I do not think it makes sense to merge support for the dataset in. Rather, your dataset should live in its own repository and provide support scripts for various other algorithms, potentially including DSAC* (although your paper does not report DSAC* results as far as I can see, nor does it cite the DSAC* paper).

The purpose of the DSAC* repository is to ensure reproducibility of our published results. We did not provide results for your dataset in our publication, and we do not have the capacity to provide "official" results in an addendum.

Best,
Eric

**Comment by clementinboittiaux** [comment]
Hi Eric,

Thanks!
I completely understand, I simply misinterpreted the repository's objective - sorry about that. It will remain on my fork then!

Best,

Clémentin

**Pull request closed without merging**
